# Generated by Django 4.2.22 on 2025-06-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name_plural': 'Students'},
        ),
    ]
